"""Agent Planner — creates multi-step execution plans from user requests.

IMPORTANT: This planner NEVER hard-codes document content.
All content (PDFs, presentations, spreadsheets, DOCX) is generated by Qwen
through the content generation tools in Step 1, then rendered in Step 2.

Plan shapes:

  Direct creation request (no document_id):
    Step 1: generate_document_content / generate_presentation_content / generate_spreadsheet_content
    Step 2: create_pdf / create_ppt / create_excel / create_document  (depends_on=[step_1])

  Document intelligence request (requires document_id):
    Step 1: generate_notes / generate_quiz / generate_flashcards / summarize_document
    Step N: export_study_result  (depends_on=[step_N-1])
"""

from __future__ import annotations

from backend.agent.models import AgentPlan, AgentRequest, AgentStep
from backend.core.tools import list_tools


EXPORT_FORMATS = (
    ('excel', 'xlsx'),
    ('xlsx', 'xlsx'),
    ('pptx', 'pptx'),
    ('powerpoint', 'pptx'),
    ('ppt', 'pptx'),
    ('docx', 'docx'),
    ('word', 'docx'),
    ('document', 'docx'),
    ('pdf', 'pdf'),
)


def _count_requested(text: str, default: int) -> int:
    for token in ('20', '15', '10', '5'):
        if token in text:
            return int(token)
    return default


def _wanted_export_formats(text: str) -> list[str]:
    formats: list[str] = []
    for keyword, format_name in EXPORT_FORMATS:
        if keyword in text and format_name not in formats:
            formats.append(format_name)
    return formats


def _preferred_export_source(step_tools: list[str], export_format: str) -> int:
    if export_format == 'xlsx':
        for index, tool in enumerate(step_tools, start=1):
            if tool in {'generate_quiz', 'generate_flashcards'}:
                return index
    if export_format in {'pptx', 'pdf', 'docx'}:
        for index, tool in enumerate(step_tools, start=1):
            if tool in {'generate_notes', 'summarize_document'}:
                return index
    return len(step_tools)


def _extract_topic(message: str) -> str:
    """Extract the topic from a creation request like 'Create a PDF about X'."""
    text = message.strip()
    # Try 'about X' pattern first
    lower = text.lower()
    for marker in (' about ', ' on ', ' regarding ', ' covering ', ' explaining '):
        idx = lower.find(marker)
        if idx >= 0:
            return text[idx + len(marker):].strip().rstrip('.')
    # Strip creation verbs and format words from the front
    words_to_strip = {
        'create', 'make', 'generate', 'write', 'build', 'produce', 'draft',
        'a', 'an', 'the', 'detailed', 'comprehensive', 'complete',
        'pdf', 'excel', 'spreadsheet', 'powerpoint', 'ppt', 'presentation',
        'docx', 'word', 'document', 'notes', 'report',
    }
    words = text.split()
    while words and words[0].lower().rstrip('.,') in words_to_strip:
        words = words[1:]
    topic = ' '.join(words).strip().rstrip('.')
    return topic or text


def _infer_audience(text: str) -> str:
    if any(w in text for w in ('college', 'university', 'student', 'undergraduate')):
        return 'college students'
    if any(w in text for w in ('professional', 'expert', 'engineer', 'developer')):
        return 'professionals'
    if any(w in text for w in ('beginner', 'basic', 'intro', 'introduction')):
        return 'beginners'
    return 'general readers'


def _infer_purpose(text: str) -> str:
    """Infer a descriptive purpose from the user's request."""
    if any(w in text for w in ('study notes', 'study guide', 'revision', 'exam')):
        return 'comprehensive study notes for exam preparation'
    if any(w in text for w in ('tutorial', 'how to', 'step by step')):
        return 'step-by-step tutorial'
    if any(w in text for w in ('report', 'research')):
        return 'technical research report'
    if any(w in text for w in ('interview', 'interview prep')):
        return 'interview preparation reference'
    if any(w in text for w in ('detailed', 'comprehensive', 'thorough', 'complete')):
        return 'comprehensive educational reference'
    return 'educational reference document'


def _infer_item_type(text: str) -> str:
    if 'interview' in text:
        return 'interview questions'
    if 'mcq' in text or 'multiple choice' in text:
        return 'multiple choice questions'
    if 'quiz' in text:
        return 'quiz questions'
    if 'flashcard' in text:
        return 'flashcards'
    return 'questions'


def create_plan(request: AgentRequest) -> AgentPlan:
    text = request.message.lower()
    document_id = request.document_ids[0] if request.document_ids else None
    available_tools = set(list_tools())
    steps: list[AgentStep] = []

    # ---- Document intelligence workflow (requires uploaded document) --------
    wants_document_workflow = any(
        keyword in text
        for keyword in ('notes', 'study guide', 'summary', 'summarize', 'mcq', 'quiz', 'flashcard', 'questions')
    )
    if wants_document_workflow and not document_id:
        # Could be a standalone quiz/questions request without a document
        # Only enforce document requirement for explicit doc-workflow keywords with 'this'
        if any(kw in text for kw in ('this document', 'this pdf', 'uploaded', 'from the')):
            raise ValueError('A document_id is required for document intelligence workflows')

    wants_notes = any(keyword in text for keyword in ('notes', 'study guide', 'summary', 'summarize'))
    wants_quiz = any(keyword in text for keyword in ('quiz', 'mcq', 'questions'))
    wants_flashcards = 'flashcard' in text

    if document_id and wants_document_workflow:
        if wants_notes:
            steps.append(AgentStep(
                id='step_1', tool='generate_notes', title='Generate study notes',
                arguments={'document_id': document_id, 'style': 'exam'},
            ))
        elif wants_quiz:
            steps.append(AgentStep(
                id='step_1', tool='generate_quiz',
                arguments={'document_id': document_id, 'count': _count_requested(text, 10), 'difficulty': 'mixed'},
            ))
        elif wants_flashcards:
            steps.append(AgentStep(
                id='step_1', tool='generate_flashcards', title='Generate flashcards',
                arguments={'document_id': document_id, 'count': _count_requested(text, 20)},
            ))
        elif 'summary' in text or 'summarize' in text:
            steps.append(AgentStep(
                id='step_1', tool='summarize_document',
                arguments={'document_id': document_id},
            ))
        else:
            steps.append(AgentStep(
                id='step_1', tool='generate_notes', title='Generate notes',
                arguments={'document_id': document_id, 'style': 'exam'},
            ))

        if wants_notes and wants_quiz:
            steps.append(AgentStep(
                id='step_2', tool='generate_quiz', depends_on=['step_1'],
                arguments={'document_id': document_id, 'count': _count_requested(text, 10), 'difficulty': 'mixed'},
            ))
        elif wants_notes and wants_flashcards:
            steps.append(AgentStep(
                id='step_2', tool='generate_flashcards', title='Generate flashcards', depends_on=['step_1'],
                arguments={'document_id': document_id, 'count': _count_requested(text, 20)},
            ))

    # ---- Direct creation requests (no document needed, Qwen generates content) ----
    if not steps:
        topic = _extract_topic(request.message)
        audience = _infer_audience(text)
        purpose = _infer_purpose(text)

        if ('docx' in text or 'word document' in text or 'word file' in text) and 'generate_document_content' in available_tools:
            # Step 1: Qwen generates content
            steps.append(AgentStep(
                id='step_1',
                tool='generate_document_content',
                title='Generate document content',
                arguments={
                    'topic': topic,
                    'purpose': purpose,
                    'audience': audience,
                    'requirements': [],
                    'filename': 'document',
                    'request': request.message,
                },
            ))
            # Step 2: Render to DOCX using Qwen output
            steps.append(AgentStep(
                id='step_2',
                tool='create_document',
                title='Format document',
                depends_on=['step_1'],
                arguments={
                    'filename': 'agent-result.docx',
                    'title': '$step_1.result.title',
                    'paragraphs': '$step_1.result.paragraphs',
                },
            ))

        elif ('ppt' in text or 'powerpoint' in text or 'presentation' in text) and 'generate_presentation_content' in available_tools:
            steps.append(AgentStep(
                id='step_1',
                tool='generate_presentation_content',
                title='Generate presentation content',
                arguments={
                    'topic': topic,
                    'purpose': purpose,
                    'audience': audience,
                    'filename': 'presentation',
                    'request': request.message,
                },
            ))
            steps.append(AgentStep(
                id='step_2',
                tool='create_ppt',
                title='Build presentation',
                depends_on=['step_1'],
                arguments={
                    'filename': 'agent-result.pptx',
                    'presentation_title': '$step_1.result.title',
                    'slides': '$step_1.result.slides_for_generator',
                },
            ))

        elif ('excel' in text or 'spreadsheet' in text or 'xlsx' in text) and 'generate_spreadsheet_content' in available_tools:
            count = _count_requested(text, 20)
            item_type = _infer_item_type(text)
            steps.append(AgentStep(
                id='step_1',
                tool='generate_spreadsheet_content',
                title='Generate spreadsheet content',
                arguments={
                    'topic': topic,
                    'count': count,
                    'item_type': item_type,
                    'filename': 'spreadsheet',
                },
            ))
            steps.append(AgentStep(
                id='step_2',
                tool='create_excel',
                title='Format spreadsheet',
                depends_on=['step_1'],
                arguments={
                    'filename': 'agent-result.xlsx',
                    'sheet_name': '$step_1.result.sheet_name',
                    'columns': '$step_1.result.columns',
                    'rows': '$step_1.result.generator_rows',
                },
            ))

        elif 'pdf' in text and 'generate_document_content' in available_tools:
            steps.append(AgentStep(
                id='step_1',
                tool='generate_document_content',
                title='Generate detailed content',
                arguments={
                    'topic': topic,
                    'purpose': purpose,
                    'audience': audience,
                    'requirements': [],
                    'filename': 'document',
                    'request': request.message,
                },
            ))
            steps.append(AgentStep(
                id='step_2',
                tool='create_pdf',
                title='Build PDF',
                depends_on=['step_1'],
                arguments={
                    'filename': 'agent-result.pdf',
                    'title': '$step_1.result.title',
                    'content': '$step_1.result.plain_text',
                },
            ))

        else:
            raise ValueError('Request is not a supported bounded workflow')

    # ---- Append export steps for document intelligence workflows -----------
    export_formats = _wanted_export_formats(text)
    if steps and (steps[0].tool.startswith('generate_') and steps[0].tool in {
        'generate_notes', 'generate_quiz', 'generate_flashcards', 'summarize_document',
    }):
        if not export_formats:
            export_formats = ['pdf']
        step_tools = [
            step.tool for step in steps
            if step.tool in {'generate_notes', 'summarize_document', 'generate_quiz', 'generate_flashcards'}
        ]
        next_step_index = len(steps) + 1
        for format_name in export_formats:
            source_index = _preferred_export_source(step_tools, format_name)
            source_step_id = f'step_{source_index}'
            steps.append(AgentStep(
                id=f'step_{next_step_index}',
                tool='export_study_result',
                title=f'Export to {format_name.upper()}',
                depends_on=[source_step_id],
                arguments={
                    'result': f'${source_step_id}.result',
                    'format': format_name,
                    'filename': f'agent-study-result.{format_name}',
                },
            ))
            next_step_index += 1

    return AgentPlan(goal=request.message, steps=steps)
